[Settings]

[[redirects]]
  from = "http://yassineimounachen.com/*"
  to = "https://yassine.im/:splat"
  force = true

[[redirects]]
  from = "https://yassineimounachen.com/*"
  to = "https://yassine.im/:splat"
  force = true

[[redirects]]
  from = "http://www.yassineimounachen.com/*"
  to = "https://yassine.im/:splat"
  force = true

[[redirects]]
  from = "https://www.yassineimounachen.com/*"
  to = "https://yassine.im/:splat"
  force = true

[[redirects]]
  from = "http://yassine-im.netlify.com/*"
  to = "https://yassine.im/:splat"
  force = true

[[redirects]]
  from = "https://yassine-im.netlify.com/*"
  to = "https://yassine.im/:splat"
  force = true